---
title: Lập trình hướng - đối tượng với Python
jupyter: python3
---



## Giới thiệu

- `Ngôn ngữ tự nhiên (natural language)` là ngôn ngữ do con người sáng tạo qua nhiều năm để nghe, nói, đọc, viết. 
- `Formal language` là ngôn ngữ do con người tạo ra để phục vụ các ứng dụng nhất định
        - `Token` là đơn vị của ngôn ngữ. Ví dụ: 3*8=1&8, & không phải là token được sử dụng trong phép toán
        - `Structure` là cấu trúc hay ngữ pháp của ngôn ngữ (syntax)
- Khi đọc 1 statement, ta cần phải tìm hiểu cấu trúc của statement đó, quá trình này gọi là `parsing`

**Object-oriented programming** - lập trình hướng đối tượng là mô hình lập trình (programming paradigm) rất phổ biến hiện nay.<br>
Các ngôn ngữ truyền thống như C, Fortran, Matlab..được viết theo mô hình **Procedural Programming** - lập trình hướng thủ tục, trong đó các câu lệnh, biến và data được chạy một cách độc lập hoặc được nhóm vào trong một hàm.

Ngược lại với phương pháp trên, với **OOP**, `data`, `function` và `variable` đều được *đóng gói* trong `object`, khi đó chúng ta gọi function là **method**. **Python** là ngôn ngữ kết hợp cả 2 phương pháp này tuy nhiên nhìn chung thì **Python** nghiêng về phong cách **OOP** hơn.

Hai khái niệm quan trọng nhất trong phần này là `Class` và `Object`, chúng ta sẽ thử tìm hiểu xem nó là gì qua các phần ở dưới.

## Objects

> *In Python, almost everything is an object, with its properties and methods.*<br>

Trong Python, object bao gồm các thành phần:
- Type - Kiểu dữ liệu
- ID (unique) - Dùng để xác định vị trí của đối tượng trong memory 
- Data
- Methods

### Type - kiểu dữ liệu

Về các kiểu dữ liệu cơ bản, chúng ta đã nắm vững ở chương 1

```{python}
s = 'This is a string'
type(s)
```

Object cũng có thể là function

```{python}
def f(x): 
    return x**2
f
```

```{python}
type(f)
```

hoặc thậm chí là `module`

```{python}
import math
math
```

```{python}
type(math)
```

### Identity

Mọi `object` trong Python đều có 1 id unique - mỗi id tương ứng với 1 vị trí trong memory, có thể lấy id này qua hàm id

```{python}
x = 2.5
y = 2.5
id(x)
```

```{python}
id(y)
```

```{python}
x == y 
```

```{python}
x is y
```

Ở vd trên, x và y có cùng giá trị, tuy nhiên ko phải cùng 1 object

```{python}
z = x
id(z)
```

```{python}
z is x
```

x được gán cho z nên z và x sẽ có chung 1 id - *chia sẻ tham chiếu đến bộ nhớ chứ ko tạo ra 1 ô nhớ mới*

### Object Content - Data & Attributes

Nếu chúng ta gán `x=42` - có nghĩa là tạo 1 object x có kiểu dữ liệu `int` và giá trị là `42`, thực tế thì object x chứa nhiều nội dung hơn thế, có thể xem vd dưới

```{python}
x = 42
x.imag
```

```{python}
x.__class__
```

Thử gõ `x.` sau đó ấn `Tab` chúng ta sẽ thấy hiện lên rất nhiều thông tin liên quan đến object vừa tạo, những thông tin này được gọi là `attribute` của `object`
- e.g. `imag` và `__class__` là các attribute của x

### Methods

Trong các `attribute` của `object`, thuộc tính `function` được gọi là `method`

```{python}
x = ['foo', 'bar']
x.append(3) 
x
```

Khi gọi method, method sẽ xử lý trên data của object hoặc data được nhập vào

```{python}
x = ['a', 'b']
x.append('c')
s = 'This is a string'
s.upper()
```

**Tóm tắt:**

|      Tên   | Purpose         | Similar to |      Syntax        |
| -----------|:---------------:|:----------:|-------------------:|
| Attribute  | Lưu trữ dữ liệu | Variable   | object.attribute() |
| Method     | Process dữ liệu |   Function | object.method()    |

## Class

Phần trước chúng ta đã giới thiệu cơ bản về `Object-oriented Programming` và tìm hiểu về `Object`, phần này sẽ tìm hiểu cách tạo 1 object. Để làm được việc này, **Python** cung cấp 1 kiểu dữ liệu gọi là **Class**, hiểu đơn giản **Class** giống như 1 *bản thiết kế/ template* để tạo ra **Object** và trong bản thiết kế đó chúng ta có thể chỉ rõ được những đặc điểm mà mình mong muốn. 

Hay nói cách khác `Class` là kiểu dữ liệu tự tạo ra. Dữ liệu được chứa trong `Class` được gọi là `attribute`

```{python}
class Point:
    """Kiểu dữ liệu 2D
    Attributes: x, y
    """
```

```{python}
Point
```

Vì `Point` được lưu trữ ở global environment nên tên đầy đủ sẽ là `__main__.Point`. Quá trình tạo object mới được gọi là `instantiation`  hay object là `instance` mới của `class`

```{python}
blank = Point()
```

```{python}
# Thêm attribute cho class
blank.x = 3
blank.y = 4
```

### Methods

`Methods` là hàm được sử dụng trong class. Bản chất của `methods` là hàm nhưng có các điểm khác biệt sau

- Methods được khai báo ngay trong class
- Ngữ pháp để gọi methods sẽ khác so với với gọi function

```{python}
# Cách viết thường
class Time:
    """Trả ra kết qua time"""
    
def print_time(time):
    print('%.2d:%.2d:%.2d' % (time.hour, time.minute, time.second))
```

```{python}
start = Time()
```

```{python}
# Assign attribute
start.hour = 9
start.minute = 45
start.second = 20
print_time(start)
```

Với cách viết trên, ta phải để time dưới dạng argument. Tuy nhiên, ta có thể thay đổi cách viết bằng cách tạo methods trong class như sau.

```{python}
class Time:
    """Trả ra thời gian"""
    def print_time(time):
        print('%.2d:%.2d:%.2d' % (time.hour, time.minute, time.second))
```

```{python}
start = Time()
start.hour = 9
start.minute = 45
start.second = 20
print_time(start)
```

```{python}
# Sử dụng methods
Time.print_time(start)
```

```{python}
start.print_time()
```

### __Init__ method 

- `__init__` được sử dụng khi tạo ra object đầu tiên trong class
- `selft` là method được sử dụng khi tạo ra đối tượng mới (instance)

```{python}
class Time:
    def __init__(self, hour = 0, minute = 0, second = 0):
        self.hour = hour
        self.minute = minute
        self.second = second
    def print_time(time):
        print('%.2d:%.2d:%.2d' % (time.hour, time.minute, time.second))
```

```{python}
start = Time()
```

```{python}
start.print_time()
```

Khi sử dụng class với __init__, ta có thể xây dựng tham số

```{python}
Time(9, 45).print_time()
```

**Lưu ý**: Khi chưa sử dụng __str__ method, khi print class sẽ không trả ra kết quả mong muốn

```{python}
print(Time(9, 45))
```

### `__str__` method

- `__str__` là method cho phép hiển thị giá trị của instance

```{python}
class Time:
    def __init__(self, hour = 0, minute = 0, second = 0):
        self.hour = hour
        self.minute = minute
        self.second = second
    def print_time(time):
        print('%.2d:%.2d:%.2d' % (time.hour, time.minute, time.second))
    def __str__(time):
        return '%.2d:%.2d:%.2d' % (time.hour, time.minute, time.second)
```

```{python}
print(Time(4,5,8))
```

```{python}
Time(4,5,6).print_time()
```

## Tài liệu tham khảo

- Think Python

